CREATE TABLE LOGIN (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	EMAIL VARCHAR(255) UNIQUE,
	PASSWORD VARCHAR(255),
	CUSTOMER_ID VARCHAR(6)
);

CREATE TABLE LOGIN_TEMP (
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	TEMP_UUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	EXP_DATE SMALLDATETIME NOT NULL DEFAULT CAST(DATEADD(hh,24,GETDATE()) AS SMALLDATETIME),
	VALUE VARCHAR(255)
);


CREATE TABLE CUSTOMERS (
	CUSTOMER_ID VARCHAR(6) NOT NULL UNIQUE PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(60)
);

INSERT INTO CUSTOMERS VALUES ('000001', 'ADMIN');
INSERT INTO CUSTOMERS VALUES ('000002', 'USER 1');
INSERT INTO CUSTOMERS VALUES ('000003', 'USER 2');